# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn clean
  build2:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: exit 1
  build3:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run: mvn clean              
workflows:
  version: 2
  test:
    jobs:
      - build
      - build2
      - build3:
          requires:
            - build
    
